import React from 'react';
import {ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions} from 'react-native';
import {useFocusEffect, useIsFocused, useRoute, useNavigation} from '@react-navigation/native';
import {useTranslation} from 'react-i18next';
import {ListFilter, CalendarX2, RotateCcw, Search, UserRound, UsersRound, ChevronDown} from 'lucide-react-native';
import {getMe, getPlayerPoolOptions, type PlayerPoolFilterOptions} from '@/services/api';
import {emptySimilarFilters, findSimilarPlayers, getSimilarEligibility, nextSimilarCount, similarFiltersValid, similarResultLimit, similarMoreAction, type SimilarFilters, type SimilarMatch, type SimilarReference} from '@/services/similarPlayers';
import {useWorkspaceActionAd} from '@/ads/useWorkspaceActionAd';
import {Action, Badge, SelectField, Selector, Status} from '@/components/LeaguePerformanceControls';
import {ContractDateFilter, ContractStatusFilter} from '@/components/ContractFilters';
import {TutorialPageGuide} from '@/components/Tutorial';
import SimilarPlayersUpgradeModal from '@/components/SimilarPlayersUpgradeModal';
import LeaguePlayerCardModal from '@/components/LeaguePlayerCardModal';
import {portfolioViewportHeight} from '@/utils/portfolioLayout';
import {ACCENT, BG, CARD, DANGER, FRAME_HEADING, FRAME_STRIPE, FRAME_TITLE, LINE, MUTED, PANEL, TEXT} from '@/theme';

function Frame({title, Icon, action, children}:{title:string;Icon:typeof Search;action?:React.ReactNode;children:React.ReactNode}) {
  return <View style={s.frame}><View style={FRAME_STRIPE}/><View style={[FRAME_HEADING,{marginBottom:16}]}><Icon size={20} color={ACCENT}/><Text style={[FRAME_TITLE,{flex:1}]}>{title}</Text>{action}</View>{children}</View>;
}
export default function SimilarPlayersScreen(){
  const {t,i18n}=useTranslation(),tr=i18n.language.startsWith('tr'),focused=useIsFocused();
  const {width,height,fontScale}=useWindowDimensions(),pairColumns=(width-66)/Math.max(1,fontScale)>=240;
  const route=useRoute<any>(),nav=useNavigation<any>(),ads=useWorkspaceActionAd();
  const resultScroll=React.useRef<ScrollView>(null),revealNewRows=React.useRef(false);
  const scroll=React.useRef<ScrollView>(null),mounted=React.useRef(true),epoch=React.useRef(0),searchLock=React.useRef(false);
  const [reference,setReference]=React.useState<SimilarReference|null>(route.params?.reference??null),[eligibility,setEligibility]=React.useState<'idle'|'checking'|'eligible'|'insufficient'|'error'>('idle');
  const [filters,setFilters]=React.useState<SimilarFilters>(emptySimilarFilters),[minAge,setMinAge]=React.useState(''),[maxAge,setMaxAge]=React.useState('');
  const [options,setOptions]=React.useState<PlayerPoolFilterOptions|null>(null),[optionsError,setOptionsError]=React.useState(false),[optionsRetry,setOptionsRetry]=React.useState(0),[selector,setSelector]=React.useState<'nationality'|'league'|null>(null);
  const [results,setResults]=React.useState<SimilarMatch[]|null>(null),[visibleCount,setVisibleCount]=React.useState(3),[limit,setLimit]=React.useState(3),[loading,setLoading]=React.useState(false),[error,setError]=React.useState(''),[searchedKey,setSearchedKey]=React.useState(''),[card,setCard]=React.useState<SimilarReference|null>(null);
  const [upgrade,setUpgrade]=React.useState<'plus'|'pro'|'done'|null>(null);
  React.useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;epoch.current++;};},[]);
  useFocusEffect(React.useCallback(()=>{let active=true;getMe().then(me=>{if(active){const cap=similarResultLimit(me.plan);setLimit(cap);setResults(rows=>rows?rows.slice(0,cap):null);setVisibleCount(count=>Math.min(count,cap));}}).catch(()=>{});return()=>{active=false;epoch.current++;setCard(null);setUpgrade(null);};},[]));
  React.useEffect(()=>{if(!reference)return;let active=true;setOptionsError(false);getPlayerPoolOptions().then(value=>{if(active)setOptions(value);}).catch(()=>{if(active)setOptionsError(true);});return()=>{active=false;};},[optionsRetry,!!reference]);
  React.useEffect(()=>{if(route.params?.reference){setReference(route.params.reference);setResults(null);setError('');setSearchedKey('');setVisibleCount(3);setFilters(emptySimilarFilters());setMinAge('');setMaxAge('');}},[route.params?.reference?.id,route.params?.visitKey]);
  React.useEffect(()=>{if(!reference||!focused)return;let alive=true;setEligibility('checking');getSimilarEligibility(reference.id).then(value=>{if(alive)setEligibility(value.eligible?'eligible':'insufficient');}).catch(()=>{if(alive)setEligibility('error');});return()=>{alive=false;};},[reference?.id,focused,optionsRetry]);
  const criteria:SimilarFilters={...filters,minAge:minAge.trim()?Number(minAge):undefined,maxAge:maxAge.trim()?Number(maxAge):undefined};
  const criteriaValid=similarFiltersValid(criteria)&&(!minAge||/^\d+$/.test(minAge))&&(!maxAge||/^\d+$/.test(maxAge));
  const currentKey=JSON.stringify([reference?.id,criteria]);
  async function search(){
    if(!reference||eligibility!=='eligible'||!criteriaValid||searchLock.current)return;
    searchLock.current=true;setLoading(true);setError('');const version=++epoch.current,source=reference.id,input=criteria,key=currentKey;
    try{await ads.run('similarPlayersSearch',async()=>{const value=await findSimilarPlayers(source,input);if(mounted.current&&version===epoch.current){setResults(value.rows);setLimit(value.limit);setVisibleCount(3);setSearchedKey(key);}});}
    catch(reason){if(mounted.current&&version===epoch.current){const message=reason instanceof Error?reason.message:String(reason);setError(message.includes('similarity_source_insufficient')?(tr?'Bu oyuncu için güvenilir benzerlik analizi yapmaya yetecek veri yok.':'This player does not have enough data for reliable similarity analysis.'):(tr?'Benzer oyuncular yüklenemedi. Lütfen tekrar dene.':'Similar players could not be loaded. Please try again.'));}}
    finally{searchLock.current=false;if(mounted.current)setLoading(false);}
  }
  function showMore(){const action=similarMoreAction(limit,shown.length,results?.length||0);if(action==='more'){revealNewRows.current=true;setVisibleCount(count=>nextSimilarCount(count,Math.min(results?.length||0,limit)));}else if(action==='plus'||action==='pro')setUpgrade(action);else setUpgrade('done');}
  function reset(){setFilters(emptySimilarFilters());setMinAge('');setMaxAge('');}
  function toggleOption(value:string){if(!selector)return;setFilters(current=>{const values=current[selector];if(!values.includes(value)&&values.length>=50){Alert.alert(tr?'Seçim sınırı':'Selection limit',tr?'En fazla 50 seçenek seçebilirsin.':'Select up to 50 options.');return current;}return {...current,[selector]:value?(values.includes(value)?values.filter(v=>v!==value):[...values,value]):[]};});}
  const shown=(results||[]).slice(0,Math.min(visibleCount,limit));
  return <ScrollView ref={scroll} style={{flex:1,backgroundColor:BG}} contentContainerStyle={s.page} keyboardShouldPersistTaps="handled">
    {!reference?<Frame title={t('similarPlayersWorkspace')} Icon={UsersRound}><View style={{gap:16}}><Text style={s.caption}>{tr?'Oyuncu kartındaki “Benzeri” butonuna basarak alternatif profilleri keşfet. Seçtiğin oyuncunun kartı, benzerlik kriterleri ve en yakın profiller burada görünecek.':'Press Similar on a player card to explore alternatives. The selected player card, similarity criteria and closest profiles will appear here.'}</Text><Action label={tr?'Oyuncu Havuzu’na Git':'Go to Player Pool'} onPress={()=>nav.navigate('Strategy')}/></View></Frame>:<>
    <Frame title={tr?'Oyuncu Kartı':'Player Card'} Icon={UserRound}>
      <LeaguePlayerCardModal key={reference.id} initialEntry={reference} inline actionsDisabled={loading||ads.busy} onClose={()=>{}}/>
      {eligibility==='checking'&&<ActivityIndicator color={ACCENT} style={{paddingTop:12}}/>}
      {eligibility==='insufficient'&&<View style={{gap:12,marginTop:14}}><Status text={tr?'Bu oyuncu için güvenilir benzerlik analizi yapmaya yetecek veri bulunmuyor. Oyuncu Havuzu’ndaki başka bir kartın Benzeri butonuyla devam et.':'There is not enough data for reliable similarity analysis. Continue with Similar on another card in Player Pool.'}/><Action label={tr?'Oyuncu Havuzu’na Git':'Go to Player Pool'} onPress={()=>nav.navigate('Strategy')}/></View>}
      {eligibility==='error'&&<Action label={tr?'Veri kontrolünü tekrar dene':'Retry data check'} onPress={()=>setOptionsRetry(value=>value+1)}/>}
    </Frame>
    {eligibility==='eligible'&&<>
    <TutorialPageGuide page="similarPlayers" frame={0} onShow={y=>scroll.current?.scrollTo({y:Math.max(0,y-12),animated:true})}/>
    <Frame title={t('similarPlayersFiltersTitle')} Icon={ListFilter} action={<View style={{flexDirection:'row',alignItems:'center',gap:20}}><Pressable accessibilityRole="button" accessibilityLabel={tr?'Tarihleri temizle':'Clear dates'} disabled={loading||ads.busy||(!filters.contractEndDate&&!filters.loanEndDate)} style={(!filters.contractEndDate&&!filters.loanEndDate)||loading||ads.busy?{opacity:.4}:undefined} hitSlop={8} onPress={()=>setFilters(current=>({...current,contractEndDate:'',loanEndDate:''}))}><CalendarX2 size={20} color={ACCENT}/></Pressable><Pressable accessibilityRole="button" accessibilityLabel={tr?'Filtreleri temizle':'Clear filters'} disabled={loading} onPress={reset} hitSlop={10}><RotateCcw size={20} color={DANGER}/></Pressable></View>}>
      <View style={{gap:14}}><View style={[s.filterPair,!pairColumns&&{flexDirection:'column'}]}><View style={[s.filterCell,!pairColumns&&{flex:0}]}><SelectField compact additionalCount={Math.max(0,filters.nationality.length-1)} label={tr?'Ülke / Uyruk':'Country / Nationality'} value={filters.nationality[0]||(tr?'Çoklu seçim':'Multiple selections')} onPress={()=>{if(!loading&&!ads.busy)setSelector('nationality');}}/></View><View style={[s.filterCell,!pairColumns&&{flex:0}]}><Text style={s.caption}>{tr?'Yaş (Min / Maks)':'Age (Min / Max)'}</Text><View style={s.range}><View style={{flex:1,gap:7}}><TextInput accessibilityLabel={tr?'Minimum yaş':'Minimum age'} keyboardType="number-pad" value={minAge} onChangeText={setMinAge} placeholder="Min" placeholderTextColor={MUTED} style={[s.input,{paddingHorizontal:8}]} maxLength={2}/></View><View style={{flex:1,gap:7}}><TextInput accessibilityLabel={tr?'Maksimum yaş':'Maximum age'} keyboardType="number-pad" value={maxAge} onChangeText={setMaxAge} placeholder={tr?'Maks':'Max'} placeholderTextColor={MUTED} style={[s.input,{paddingHorizontal:8}]} maxLength={2}/></View></View></View></View>
      {!criteriaValid&&<Text style={{color:DANGER,fontSize:12}}>{tr?'Yaş aralığı 14–60 olmalı; minimum yaş maksimumdan büyük olamaz.':'Ages must be between 14 and 60, with minimum no greater than maximum.'}</Text>}
      <View style={[s.filterPair,!pairColumns&&{flexDirection:'column'}]}><View style={[s.filterCell,!pairColumns&&{flex:0}]}><SelectField compact additionalCount={Math.max(0,filters.league.length-1)} label={tr?'Lig':'League'} value={filters.league[0]||(tr?'Çoklu seçim':'Multiple selections')} onPress={()=>{if(!loading&&!ads.busy)setSelector('league');}}/></View><View style={[s.filterCell,!pairColumns&&{flex:0}]}><ContractStatusFilter aligned value={filters.contractStatus} disabled={loading} onChange={value=>setFilters(current=>({...current,contractStatus:value,loanEndDate:value==='permanent'?'':current.loanEndDate}))}/></View></View>
      <View style={[s.filterPair,!pairColumns&&{flexDirection:'column'}]}><View style={[s.filterCell,!pairColumns&&{flex:0}]}><ContractDateFilter aligned testID="similar-contract-expiry" label={tr?'Bonservis bitiş':'Contract Expiry'} value={filters.contractEndDate} disabled={loading} onChange={value=>setFilters(current=>({...current,contractEndDate:value}))}/></View><View style={[s.filterCell,!pairColumns&&{flex:0}]}><ContractDateFilter aligned testID="similar-loan-expiry" label={tr?'Kiralık bitiş':'Loan Expiry'} value={filters.loanEndDate} disabled={loading||filters.contractStatus==='permanent'} onChange={value=>setFilters(current=>({...current,loanEndDate:value}))}/></View></View>
      {optionsError&&<Action label={tr?'Filtre seçeneklerini yeniden yükle':'Reload filter options'} disabled={loading} onPress={()=>setOptionsRetry(v=>v+1)}/>}
      <Action icon={<UsersRound size={18} color={ACCENT}/>} label={loading?(tr?'Benzer oyuncular bulunuyor…':'Finding similar players…'):(tr?'Benzer Oyuncuları Bul':'Find Similar Players')} disabled={!reference||eligibility!=='eligible'||!criteriaValid||loading||ads.busy} onPress={()=>void search()}/>
      {results&&currentKey!==searchedKey&&<Text style={s.caption}>{tr?'Kriterler değişti. Sonuçları güncellemek için yeniden arama yap.':'Criteria changed. Run another search to update the results.'}</Text>}</View>
    </Frame>
    <TutorialPageGuide page="similarPlayers" frame={1} onShow={y=>scroll.current?.scrollTo({y:Math.max(0,y-12),animated:true})}/>
    {(results!==null||loading||!!error)&&<Frame title={t('similarPlayersResultsTitle')} Icon={UsersRound}>
      <View style={{gap:12}}><Text style={s.caption}>{tr?`Sonuçlar üçerli gösterilir. Planın en fazla ${limit} oyuncuyu kapsar.`:`Results appear in groups of three. Your plan includes up to ${limit} players.`}</Text>
      {!!error&&<View style={{gap:10}}><Text style={{color:DANGER}}>{error}</Text><Action label={tr?'Tekrar Dene':'Retry'} disabled={loading} onPress={()=>void search()}/></View>}
      {loading?<ActivityIndicator color={ACCENT} style={{padding:24}}/>:results===null?<Status text={tr?'Referans oyuncunu seçip Benzer Oyuncuları Bul butonuna bas.':'Choose your reference and press Find Similar Players.'}/>:shown.length?<ScrollView ref={resultScroll} onContentSizeChange={()=>{if(revealNewRows.current){revealNewRows.current=false;resultScroll.current?.scrollToEnd({animated:true});}}} nestedScrollEnabled bounces={false} keyboardShouldPersistTaps="handled" style={{maxHeight:portfolioViewportHeight(height)}} contentContainerStyle={{gap:8,paddingRight:5,paddingVertical:4}}>{shown.map((match,index)=><Pressable key={match.entry.id} accessibilityRole="button" accessibilityLabel={`${match.entry.player.name}, ${match.similarity}%`} onPress={()=>setCard(match.entry)} style={({pressed})=>[s.row,card?.id===match.entry.id&&s.selected,pressed&&s.pressed]}><Text style={s.rank}>{index+1}</Text><Badge player url={match.entry.player.meta?.imageUrl} size={42}/><View style={{flex:1,gap:5}}><Text style={s.name}>{match.entry.player.name}</Text><Text style={s.caption}>{match.entry.player.meta?.team||'—'} · {match.entry.player.meta?.nationality||'—'}</Text><Text style={s.caption}>{tr?'Ortak Veri Kapsamı':'Shared Data Coverage'}: %{match.coverage}</Text></View><View style={{alignItems:'flex-end',gap:5}}><Text style={s.score}>%{match.similarity}</Text><Text style={s.caption}>{tr?'Benzerlik':'Similarity'}</Text></View></Pressable>)}</ScrollView>:<Status text={tr?'Bu kriterlere ve veri koşullarına uyan benzer oyuncu bulunamadı. Filtrelerini genişletip tekrar dene.':'No similar players meet these criteria and data requirements. Broaden your filters and try again.'}/>}
      {results&&shown.length>0&&<Text accessibilityLiveRegion="polite" style={[s.caption,{color:ACCENT,textAlign:'center',fontWeight:'700'}]}>{tr?`Gösterilen Oyuncular: ${shown.length} / ${Math.min(results.length,limit)}`:`Players Shown: ${shown.length} / ${Math.min(results.length,limit)}`}</Text>}
      <Action icon={<ChevronDown size={18} color={ACCENT}/>} label={tr?'3 Oyuncu Daha Göster':'Show 3 More Players'} disabled={loading||ads.busy||results===null} onPress={showMore}/></View>
    </Frame>}
    </>}
    </>}
    {selector&&<Selector tr={tr} title={selector==='nationality'?(tr?'Ülke / Uyruk Seç':'Select Nationality'):(tr?'Lig Seç':'Select League')} options={[{key:'',label:tr?'Tümü / Seçimi temizle':'All / Clear selection'},...(selector==='nationality'?options?.nationalities||[]:options?.leagues||[]).map(value=>({key:value,label:`${filters[selector].includes(value)?'✓ ':''}${value}`}))]} selected="" selectedKeys={filters[selector]} searchPlaceholder={tr?'Seçeneklerde ara…':'Search options…'} onSelect={toggleOption} onClose={()=>setSelector(null)}/>}
    {focused&&card&&<LeaguePlayerCardModal key={card.id} initialEntry={card} onClose={()=>setCard(null)}/>}
    {focused&&upgrade&&<SimilarPlayersUpgradeModal required={upgrade} tr={tr} onClose={()=>setUpgrade(null)}/>}
    {ads.fallback}
  </ScrollView>;
}
const s=StyleSheet.create({page:{padding:16,gap:16,paddingBottom:40},frame:{borderWidth:1,borderColor:ACCENT,borderRadius:20,padding:16,backgroundColor:PANEL},input:{minHeight:46,borderWidth:1,borderColor:LINE,borderRadius:12,padding:12,color:TEXT,backgroundColor:CARD},caption:{color:MUTED,fontSize:12,lineHeight:18,flexShrink:1},name:{color:TEXT,fontSize:14,fontWeight:'800',flexShrink:1},link:{color:ACCENT,fontSize:12,fontWeight:'800'},row:{flexDirection:'row',alignItems:'center',gap:9,borderWidth:1,borderColor:'rgba(36,245,166,.16)',backgroundColor:'rgba(22,163,74,.055)',borderRadius:14,padding:10,minHeight:60},selected:{borderColor:ACCENT,backgroundColor:'rgba(22,163,74,.14)'},pressed:{backgroundColor:'rgba(22,163,74,.12)',transform:[{scale:.992}]},filterPair:{flexDirection:'row',alignItems:'flex-start',gap:12},filterCell:{flex:1,minWidth:0,width:'100%',gap:7},range:{flexDirection:'row',gap:12},rank:{color:ACCENT,fontSize:13,fontWeight:'800'},score:{color:ACCENT,fontSize:20,fontWeight:'900'}});
