// src/constants/countries.ts

// ISO 3166-ish list of sovereign states + a few common territories.
// Feel free to prune/adjust to your product needs.
export const COUNTRIES = [
  "Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Australia","Austria",
  "Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia",
  "Bosnia and Herzegovina","Botswana","Brazil","Brunei","Bulgaria","Burkina Faso","Burma","Burundi","Cambodia","Cameroon",
  "Canada","Central African Republic","Chad","Chile","China","Colombia","Comoros","Congo (Congo-Brazzaville)","Costa Rica",
  "Côte d’Ivoire","Croatia","Cuba","Cyprus","Czechia","Democratic Republic of the Congo","Denmark","Djibouti","Dominica",
  "Dominican Republic","Ecuador","Egypt", "England", "El Salvador","Equatorial Guinea","Eritrea","Estonia","Eswatini","Ethiopia","Fiji",
  "Finland","France","Gabon","Gambia","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau",
  "Guyana","Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Jamaica",
  "Japan","Jordan","Kazakhstan","Kenya","Kiribati","Kuwait","Kosovo","Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia",
  "Libya","Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Marshall Islands",
  "Mauritania","Mauritius","Mexico","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar",
  "Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Korea","North Macedonia","Norway",
  "Oman","Pakistan","Palau","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Qatar","Romania",
  "Russia","Rwanda","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines","Samoa","San Marino",
  "Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia",
  "Solomon Islands","Somalia","South Africa","South Korea","South Sudan","Spain","Sri Lanka","Sudan","Suriname","Sweden",
  "Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Timor-Leste","Togo","Tonga","Trinidad and Tobago",
  "Tunisia","Türkiye","Turkmenistan","Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States",
  "Uruguay","Uzbekistan","Vanuatu","Vatican City","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe",

  // (Common territories/regions often included in pickers)
  "Åland Islands","American Samoa","Anguilla","Aruba","Bermuda","Bonaire, Sint Eustatius and Saba","British Virgin Islands",
  "Cayman Islands","Christmas Island","Cocos (Keeling) Islands","Cook Islands","Curaçao","Faroe Islands","French Guiana",
  "French Polynesia","French Southern Territories","Gibraltar","Greenland","Guadeloupe","Guam","Guernsey","Hong Kong SAR China",
  "Isle of Man","Jersey","Macau SAR China","Martinique","Mayotte","Montserrat","New Caledonia","Niue","Norfolk Island",
  "Northern Mariana Islands","Pitcairn Islands","Puerto Rico","Réunion","Saint Barthélemy","Saint Helena, Ascension and Tristan da Cunha",
  "Saint Martin","Saint Pierre and Miquelon","Sint Maarten","South Georgia & South Sandwich Islands","Tokelau","Turks and Caicos Islands",
  "U.S. Outlying Islands","U.S. Virgin Islands","Wallis and Futuna","Western Sahara"
];

// Alpha-2 short codes (curated + special cases). Add more as needed.
export const COUNTRY_CODE2: Record<string, string> = {
  Afghanistan: "AFGH",
  Albania: "ALB",
  Algeria: "ALGR",
  Andorra: "ANGL",
  Anguilla: "ANGU",
  "Antigua and Barbuda": "ANTI",
  Argentina: "ARG",
  Armenia: "ARM",
  Australia: "ASTL",
  Austria: "AUST",
  Azerbaijan: "AZR",
  Bahamas: "BAMA",
  Bahrain: "BAHR",
  Bangladesh: "BANG",
  Barbados: "BRDO",
  Belarus: "BYS",
  Belgium: "BELG",
  Belize: "BLZ",
  Benin: "BENN",
  Bermuda: "BERM",
  Bhutan: "BHU",
  Bolivia: "BOL",
  "Bosnia and Herzegovina": "BIH",
  Botswana: "BOT",
  Brazil: "BRZL",
  Brunei: "BRNI",
  Bulgaria: "BULG",
  "Burkina Faso": "BURK",
  Burma: "BURM",
  Burundi: "BRND",
  Cambodia: "CBDA",
  Cameroon: "CMRN",
  Canada: "CAN",
  "Cayman Islands": "CAYI",
  "Central African Republic": "CAFR",
  Chile: "CHIL",
  China: "CHIN",
  Colombia: "COL",
  Comoros: "COMO",
  "Congo (Congo-Brazzaville)": "CONB",
  "Costa Rica": "CSTR",
  "Côte d’Ivoire": "IVCO",
  Croatia: "HRV",
  CUBA: "CUBA",
  Cyprus: "CYPR",
  Czechia: "CZEC",
  "Democratic Republic of the Congo": "DRC",
  Denmark: "DEN",
  Djibouti: "DJI",
  Dominica: "DOMN",
  "Dominican Republic": "DOMR",
  Ecuador: "ECUA",
  Egypt: "EGYP",
  England: "ENG", 
  "El Salvador": "ELSL",
  "Equatorial Guinea": "EGN",
  Eritrea: "ERI",
  Estonia: "EST",
  Eswatini: "ESW",
  Ethiopia: "ETH",
  Fiji: "FIJI",
  Finland: "FIN",
  France: "FRAN",
  Gabon: "GABN",
  Gambia: "GAM",
  Georgia: "GEO",
  Germany: "GER",
  Ghana: "GHAN",
  Greece: "GR",
  Grenada: "GREN",
  Guatemala: "GUAT",
  Guinea: "GNEA",
  "Guinea-Bissau": "GUIB",
  Guyana: "GUY",
  Haiti: "HAT",
  Honduras: "HOND",
  Hungary: "HUNG",
  Iceland: "ICLD",
  India: "IMD",
  Indonesia: "IDSA",
  Iran: "IRAN",
  Iraq: "IRAQ",
  Ireland: "IRE",
  Israel: "ISRL",
  Italy: "ITLY",
  Jamaica: "JAM",
  Japan: "JPN",
  Jordan: "JORD",
  Kazakhstan: "KAZ",
  Kenya: "KENY",
  Kiribati: "KIRI",
  Kuwait: "KUWT",
  Kosovo: "KSV",
  Kyrgyzstan: "KGZ",
  Laos: "LAOS",
  Latvia: "LATV",
  Lebanon: "LEBN",
  Lesotho: "LES",
  Liberia: "LIBR",
  Libya: "LBYA",
  Liechtenstein: "LCHT",
  Lithuania: "LITH",
  Luxembourg: "LXM",
  Madagascar: "MADG",
  Malawi: "MALW",
  Malaysia: "MLAS",
  Mexico: "MEX",
  Maldives: "MLDV",
  Mali: "MALI",
  Malta: "MLTA",
  Mauritania: "MAUR",
  Mauritius: "MRTS",
  Moldova: "MLD",
  Monaco: "MON",
  Montenegro: "MONT",
  Mongolia: "MONG",
  Morocco: "MORO",
  Mozambique: "MOZ",
  Namibia: "NAMB",
  Nauru: "NAU",
  Nepal: "NEP",
  Netherlands: "NETH",
  "New Zealand": "NZLD",
  Niger: "NIR",
  Nigeria: "NRA",
  "North Macedonia": "MKD",
  Norway: "NORW",
  Oman: "OMAN",
  Pakistan: "PKST",
  Palau: "PALA",
  Panama: "PAN",
  "Papua New Guinea": "PNG",
  Paraguay: "PARA",
  Peru: "PERU",
  Philippines: "PHIL",
  Poland: "POL",
  Portugal: "PORT",
  Qatar: "QTAR",
  Romania: "ROM",
  Russia: "RUS",
  Rwanda: "RWND",
  "Saint Kitts and Nevis": "STCN",
  "Saint Lucia": "SLCA",
  "Saint Vincent and the Grenadines": "STVN",
  Samoa: "WSAM",
  "San Marino": "SMAR",
  "Sao Tome and Principe": "STPR",
  "Saudi Arabia": "SARB",
  Senegal: "SENG",
  Serbia: "SERB",
  Seychelles: "SEYC",
  "Sierra Leone": "SLEO",
  Singapore: "SING",
  Slovakia: "SVK",
  Slovenia: "SVN",
  "South Africa": "SAFR",
  "South Korea": "SKR",
  "Solomon Islands": "SLMN",
  Spain: "SPN",
  "Sri Lanka": "SRL",
  Sudan: "SUDA",
  Suriname: "SURM",
  Sweden: "SWDN",
  Switzerland: "SWTZ",
  Syria: "SYR",
  Taiwan: "TWAN",
  Tajikistan: "TJK",
  Tanzania: "TAZN",
  Thailand: "THAI",
  "Timor-Leste": "TMOR",
  Togo: "TOGO",
  Tonga: "TONG",
  "Trinidad and Tobago": "TRIN",
  Türkiye: "TUR",
  Turkiye: "TUR",
  Turkmenistan: "TKM",
  "Turks and Caicos Islands": "TCIS",
  Tuvalu: "TUV",
  Uganda: "UGAN",
  Ukraine: "UKR",
  "United Arab Emirates": "UAE",
  "United Kingdom": "GRBR",
  "United States": "USA",
  Uruguay: "URU",
  Uzbekistan: "UZB",
  Vanuatu: "VANU",
  Venezuela: "VENZ",
  Vietnam: "VTNM",
  "Vatican City": "VTCN",
  Yemen: "YEM",
  Zambia: "ZAMB",
  Zimbabwe: "ZIMB"
};

export function countryToCode2(name?: string | null): string {
  if (!name) return '';
  const direct = COUNTRY_CODE2[name];
  if (direct) return direct;
  // Fallback: make a 3-letter code from letters in the name
  const letters = (name.normalize('NFKD').replace(/[^\p{Letter}]+/gu, ' ').trim() || '').split(/\s+/);
  if (!letters.length) return '';
  const first = letters[0].slice(0, 3).toUpperCase();
  return first;
}
