import { COUNTRIES } from '@/constants/countries';

export const PLAYER_POOL_COUNTRIES = Array.from(
  new Set(COUNTRIES.map((country) => (country === 'Türkiye' ? 'Turkey' : country))),
).sort((a, b) => a.localeCompare(b));

export const PLAYER_POOL_POSITION_OPTIONS = [
  'GK',
  'LB',
  'RB',
  'LCB',
  'RCB',
  'CB',
  'LWB',
  'RWB',
  'LM',
  'RM',
  'LDM',
  'RDM',
  'LCM',
  'RCM',
  'LAM',
  'RAM',
  'CDM',
  'CM',
  'CAM',
  'LW',
  'RW',
  'LCF',
  'RCF',
  'CF',
] as const;

export const PLAYER_POOL_TEAM_NAMES = [
  '1º Dezembro',
  '2 de Mayo',
  '2 Korriku U19',
  '3B da Amazônia W',
  'Aalborg BK',
  'Aalesund',
  'Aarau',
  'Aarhus Fremad',
  'ABC',
  'Aberdeen',
  'Abha',
  'AC Milan',
  'Academia Puerto Cabello',
  'Academico Viseu',
  'Accrington Stanley',
  'AD Marco 09',
  'Adana Demirspor',
  'Adanaspor',
  'Adelaide United',
  'Adelaide United W',
  'Admira',
  'ADO Den Haag',
  'AEK Athens',
  'AEK Athens W',
  'AEK Larnaca',
  'AEK Larnaca U19',
  'AFC',
  'AFC Bournemouth',
  'AFC Telford United',
  'AFC Totton',
  'AFC Wimbledon',
  'AGF',
  'Agram W',
  'Águia de Marabá',
  'Ahal',
  'AIK',
  'Ajaccio',
  'Ajax',
  'Ajax U19',
  'Ajman',
  'Akhmat Grozny',
  'Akron',
  'Aktobe',
  'Aktobe W',
  'Al Adalah',
  'Al Ahli',
  'Al Ahly',
  'Al Ain',
  'Al Arabi Saudi',
  'Al Bataeh',
  'Al Batin',
  'Al Bukayriyah',
  'Al Dhafra',
  'Al Duhail',
  'Al Ettifaq',
  'Al Faisaly',
  'Al Fateh',
  'Al Gharafa',
  'Al Hazm',
  'Al Hilal',
  'Al Hilal Omdurman',
  'Al Hussein',
  'Al Ittihad',
  'Al Jabalain',
  'Al Jazira',
  'Al Jubail',
  'Al Khaleej',
  'Al Khalidiyah',
  'Al Kholood',
  'Al Masry',
  'Al Najma',
  'Al Nasr',
  'Al Nassr',
  'Al Okhdoud',
  'Al Raed',
  'Al Rayyan',
  'Al Riyadh',
  'Al Sadd',
  'Al Sailiya',
  'Al Seeb',
  'Al Shabab',
  'Al Shahaniya',
  'Al Shamal SC',
  'Al Sharjah',
  'Al Shorta',
  'Al Taawoun',
  'Al Tai',
  'Al Urooba',
  'Al Wahda',
  'Al Wakrah',
  'Al Wasl',
  'Al Wihdat',
  "Al Zawra'a",
  'Al Zulfi',
  'Al-Ahli Doha',
  'Al-Arabi SC',
  'Al-Fayha',
  'Al-Orobah FC',
  'Al-Qadsiah',
  'Al-Wehda',
  'Alaniya Vladikavkaz',
  'Alanyaspor',
  'Albacete',
  'Albion',
  'Albirex Niigata',
  'Aldershot Town',
  'Aldosivi',
  'Algeria',
  'Algeria U23',
  'Alianza Atlético',
  'Alianza Lima',
  'Almere City',
  'Almería',
  'Alpendorada',
  'Altos',
  'Altrincham',
  'Aluminium Arak',
  'Alverca',
  'Always Ready',
  'Amarante',
  'Amazonas',
  'AmaZulu',
  'Amed SK',
  'América',
  'América de Cali',
  'América Mineiro',
  'América Mineiro W',
  'América RN',
  'America SE',
  'Amiens SC',
  'Amkal',
  'Anadia',
  'Anápolis',
  'Anderlecht',
  'Andijan',
  'Andorra',
  'Anenii Noi W',
  'Angers SCO',
  'Angola',
  'Ankaragücü',
  'Annecy',
  'Antalyaspor',
  'Antequera',
  'Antoniano',
  'Antwerp',
  'Anyang',
  'Aparecidense',
  'Apollon W',
  'Arab Contractors FC',
  'Araguaína',
  'Ararat-Armenia',
  'Araz',
  'Arda',
  'Arenas de Getxo',
  'Argentinos Juniors',
  'Argeş',
  'Aris',
  'Aris Limassol',
  'Arka Gdynia',
  'Arkadag',
  'Armenia',
  'Arouca',
  'Arsenal',
  'Arsenal Tula',
  'Arsenal U19',
  'Arsenal W',
  'Aruba',
  'AS Gosier',
  'ASA',
  'Ashdod',
  'Astana',
  'Asteras Tripolis',
  'Aston Villa',
  'Aston Villa U19',
  'Aston Villa W',
  'Astrakhan',
  'Atalanta',
  'Atalanta U19',
  'Athletic Club',
  'Athletic Club U19',
  'Athletico PR',
  'Athlone Town WFC W',
  'ATK Mohun Bagan',
  'Atl. Madrid U19',
  'Atlanta United',
  'Atlas',
  'Atlas Delmenhorst',
  "Atlètic Club d'Escaldes",
  'Atlètic Lleida',
  'Atlético Alagoinhas',
  'Atlético Astorga',
  'Atlético Baleares',
  'Atlético Bucaramanga',
  'Atlético CP',
  'Atlético GO',
  'Atlético Grau',
  'Atlético Madrid',
  'Atletico Madrid W',
  'Atlético Mineiro',
  'Atlético Mineiro W',
  'Atlético Nacional',
  'Atlético Progreso',
  'Atlético San Luis',
  'Atlético Tordesillas',
  'Atlético Tucumán',
  'Atromitos',
  'Aucas',
  'Auckland',
  'Auckland City',
  'Auda',
  'Audace Cerignola',
  'Audax Italiano',
  'Austin',
  'Australia',
  'Austria Klagenfurt',
  'Austria Wien',
  'Austria Wien U19',
  'Austria Wien W',
  'Auxerre',
  'Avaí',
  'Avellino',
  'Avispa Fukuoka',
  'Avranches',
  'AVS',
  'Ayr United',
  'AZ',
  'AZ U19',
  'Azerbaijan',
  'Azuaga',
  'Azuriz',
  'B 93',
  'Bahia',
  'Bahia W',
  'Bandırmaspor',
  'Barcelona',
  'Barcelona Guayaquil',
  'Barcelona U19',
  'Barcelona W',
  'Bari 1908',
  'Barnet',
  'Barnsley',
  'Basel',
  'Basel U19',
  'Bastia',
  'Bayer 04 Leverkusen',
  'Bayer Leverkusen U19',
  'Bayern Munich W',
  'Bayern U19',
  'Beijing Guoan',
  'Beitar Jerusalem',
  'Belgrano',
  'Benfica',
  'Benfica U19',
  'Beroe',
  'Beşiktaş',
  'BFC Dynamo',
  'BG Pathum United',
  'Birmingham City',
  'Blackburn Rovers',
  'Blackpool',
  'Boca Juniors',
  'Bodrum FK',
  'Bohemians 1905',
  'Bologna',
  'Bolton Wanderers',
  'Boluspor',
  'Bordeaux',
  'Borussia Dortmund',
  'Borussia Dortmund U19',
  'Borussia Mönchengladbach',
  'Botafogo',
  'Braga',
  'Bragantino',
  'Brann',
  'Brann U19',
  'Brann W',
  'Brentford',
  'Brescia',
  'Brest',
  'Brighton & Hove Albion',
  'Brighton W',
  'Bristol City',
  'Bristol Rovers',
  'Bromley',
  'Brommapojkarna',
  'Brommapojkarna U19',
  'Brøndby IF',
  'Brusque',
  'Bryne',
  'Bucheon 1995',
  'Budućnost',
  'Burgos',
  'Burnley',
  'Burton Albion',
  'BW Lohne',
  'Cádiz',
  'Caen',
  'Cagliari',
  'Cambridge United',
  'Cameroon',
  'Canada',
  'Cardiff City',
  'Cardiff City W',
  'Carlisle United',
  'Casa Pia',
  'Castellón',
  'Catanzaro',
  'Caxias',
  'Ceará',
  'Celje',
  'Celta de Vigo',
  'Celtic',
  'Central Coast Mariners',
  'Central Coast Mariners W',
  'Cercle Brugge',
  'Cerezo Osaka',
  'Cesena',
  'CF Montréal',
  'CFR Cluj',
  'Chadormalu SC',
  'Changchun Yatai',
  'Chapecoense',
  'Charlotte',
  'Charlton Athletic',
  'Chelsea',
  'Chelsea U19',
  'Chelsea W',
  'Cheltenham Town',
  'Chengdu Rongcheng',
  'Chennaiyin',
  'Cherno More',
  'Chesterfield',
  'Chicago Fire',
  'Chile',
  'China PR',
  'Chippa United',
  'Cincinnati',
  'Cittadella',
  'Clermont',
  'Club Bolívar',
  'Club Brugge',
  'Club Brugge U19',
  'Club NXT U23',
  'Cobresal',
  'Colchester United',
  'Colo-Colo',
  'Colorado Rapids',
  'Columbus Crew',
  'Como',
  'Corinthians',
  'Corinthians W',
  'Coritiba',
  'Çorum FK',
  'Cosenza',
  'Coventry City',
  'Cracovia Kraków',
  'Crawley Town',
  'Cremonese',
  'Crewe Alexandra',
  'Criciúma',
  'Cruz Azul',
  'Cruzeiro',
  'Cruzeiro W',
  'Crvena Zvezda',
  'Crvena Zvezda U19',
  'Crystal Palace',
  'Crystal Palace W',
  'CSKA Moskva',
  'CSKA Sofia',
  'Cuiabá',
  'Cultural Leonesa',
  'Cusco FC',
  'Daegu',
  'Daejeon Citizen',
  'Dallas',
  'Damac FC',
  'Danubio',
  'Darmstadt 98',
  'DC United',
  'Defensa y Justicia',
  'Degerfors',
  'Deportivo Alavés',
  'Deportivo La Coruña',
  'Derby County',
  'Dinamo Brest',
  'Dinamo Bucureşti',
  'Dinamo Minsk',
  'Dinamo Moskva',
  'Dinamo Zagreb',
  'Djurgården',
  'Doncaster Rovers',
  'Drita',
  'Dukla Praha',
  'Dundee',
  'Dundee United',
  'Dynamo Dresden',
  'Dynamo Kyiv',
  'Dynamo Kyiv U19',
  'East Bengal',
  'Eintracht Braunschweig',
  'Eintracht Frankfurt',
  'Eintracht Frankfurt U19',
  'Eintracht Frankfurt W',
  'Elche',
  'Eldense',
  'Elfsborg',
  'Elversberg',
  'Empoli',
  'Energie Cottbus',
  'ENPPI',
  'Erzgebirge Aue',
  'Erzurumspor FK',
  'ES Tunis',
  'Espanyol',
  'Estoril',
  'Estrela Amadora',
  'Estudiantes',
  'Everton',
  'Everton W',
  'Excelsior',
  'Exeter City',
  'Eyüpspor',
  'F91 Dudelange',
  'Fagiano Okayama',
  'Fakel',
  'Falkirk',
  'Famalicão',
  'Farense',
  'Farul Constanța',
  'Fatih Karagümrük',
  'FC Andorra',
  'FC Augsburg',
  'FC Barcelona',
  'FC Bayern München',
  'FC Cartagena',
  'FC Den Bosch',
  'FC Dordrecht',
  'FC Eindhoven',
  'FC Emmen',
  'FC Groningen',
  'FC København',
  'FC Köln',
  'FC Midtjylland',
  'FC Tokyo',
  'FC Twente',
  'FC Twente W',
  'FC Union Berlin',
  'FC Utrecht',
  'FC Volendam',
  'FCSB',
  'FCSB U19',
  'Fenerbahçe',
  'Ferencvárosi',
  'Feyenoord',
  'Figueirense',
  'Fiorentina',
  'Fiorentina U20',
  'Flamengo',
  'Flamengo W',
  'Fleetwood Town',
  'Fluminense',
  'Fluminense W',
  'Forest Green Rovers',
  'Fortaleza',
  'Fortuna Düsseldorf',
  'Fortuna Sittard',
  'Fredrikstad',
  'Frosinone',
  'FSV Mainz 05',
  'Fulham',
  'GAIS',
  'Galatasaray',
  'Galatasaray U19',
  'Gamba Osaka',
  'Gangwon',
  'Gaziantep F.K.',
  'Gençlerbirliği',
  'Genk',
  'Genk U19',
  'Genoa',
  'Gent',
  'Getafe',
  'Gil Vicente',
  'Gimcheon Sangmu',
  'Girona',
  'Go Ahead Eagles',
  'Godoy Cruz',
  'Górnik Zabrze',
  'Göztepe',
  'Granada',
  'Grasshopper',
  'Grazer AK',
  'Grêmio',
  'Grêmio W',
  'Grenoble Foot 38',
  'Guadalajara',
  'Guarani',
  'Guaraní',
  'Guingamp',
  'Gwangju',
  'Győri ETO',
  'Häcken',
  'Häcken W',
  'Hajduk Split',
  'Hamburger SV',
  'HamKam',
  'Hammarby',
  'Hammarby W',
  'Hannover 96',
  'Hansa Rostock',
  'Hatayspor',
  'Haugesund',
  'HB Køge',
  'Hearts',
  'Heidenheim',
  'Hellas Verona',
  'Heracles Almelo',
  'Hertha BSC',
  'Hibernian',
  'Hibernian U19',
  'Hibernian W',
  'HJK',
  'HJK U19',
  'HJK W',
  'Holstein Kiel',
  'Houston Dynamo',
  'Hradec Králové',
  'Huddersfield Town',
  'Huesca',
  'Hull City',
  'Huracán',
  'IFK Göteborg',
  'Iğdır FK',
  'Ilves',
  'Incheon United',
  'Independiente',
  'Independiente del Valle',
  'Independiente Medellín',
  'Inter',
  'Inter Miami',
  'Inter Turku',
  'Internacional',
  'Ipswich Town',
  'Ismaily',
  'İstanbul Başakşehir',
  'İstanbulspor',
  'Istra 1961',
  'Jablonec',
  'Jagiellonia Białystok',
  'Jahn Regensburg',
  'Jamshedpur',
  'Jeju United',
  'Jeonbuk Motors',
  'Johor Darul Ta\'zim',
  'Jong Ajax',
  'Jong AZ',
  'Jong PSV',
  'Juárez',
  'Junior FC',
  'Juventude',
  'Juventude W',
  'Juventus',
  'Juventus U19',
  'Juventus W',
  'KA Akureyri',
  'Kairat',
  'Kairat U19',
  'Karlsruher SC',
  'Kashima Antlers',
  'Kashiwa Reysol',
  'Kasımpaşa',
  'Kawasaki Frontale',
  'Kayserispor',
  'Keçiörengücü',
  'KF Ballkani',
  'Kilmarnock',
  'Kocaelispor',
  'Köln U19',
  'Kolos Kovalivka',
  'Konyaspor',
  'Korea Republic',
  'Korona Kielce',
  'Krasnodar',
  'Kristiansund',
  'Krylya Sovetov',
  'Kryvbas Kryvyi Rih',
  'KuPS',
  'KV Kortrijk',
  'Kyoto Sanga',
  'LA Galaxy',
  'LASK Linz',
  'Lazio',
  'LDU Quito',
  'Le Havre',
  'Le Mans',
  'Lecce',
  'Lech Poznań',
  'Leeds United',
  'Leganés',
  'Legia Warszawa',
  'Legia Warszawa U19',
  'Leicester City',
  'Leicester W',
  'Lens',
  'León',
  'Levadia',
  'Levante',
  'Leyton Orient',
  'Lillestrøm',
  'Lincoln City',
  'Linfield',
  'Liverpool',
  'Liverpool U19',
  'Liverpool W',
  'Livingston',
  'Lokomotiv Moskva',
  'Lokomotiv Plovdiv',
  'Lokomotiva Zagreb',
  'LOSC Lille',
  'Lorient',
  'Los Angeles FC',
  'Ludogorets',
  'Ludogorets U19',
  'Lugano',
  'Luton Town',
  'Luzern',
  'Lyngby Boldklub',
  'Maccabi Haifa',
  'Maccabi Haifa U19',
  'Maccabi Tel Aviv',
  'Machida Zelvia',
  'Magdeburg',
  'Málaga',
  'Mallorca',
  'Malmö FF',
  'Mamelodi Sundowns',
  'Manchester City',
  'Manchester City U19',
  'Manchester City W',
  'Manchester United',
  'Manchester United W',
  'Manisa FK',
  'Mansfield Town',
  'Maribor',
  'Marseille',
  'Mazatlán',
  'Mechelen',
  'Melbourne City',
  'Melbourne City W',
  'Melbourne Victory',
  'Melbourne Victory W',
  'Metz',
  'Middlesbrough',
  'Millwall',
  'Minnesota United',
  'Mjällby',
  'Modena',
  'Molde',
  'Monaco',
  'Monaco U19',
  'Monterrey',
  'Montpellier',
  'Monza',
  'Moreirense',
  'Motherwell',
  'Motor Lublin',
  'Mumbai City',
  'MVV Maastricht',
  'NAC Breda',
  'Nacional',
  'Nagoya Grampus',
  'Nantes',
  'Nantes U19',
  'Napoli',
  'Napoli U19',
  'Nashville SC',
  'NEC Nijmegen',
  'Necaxa',
  'NEOM SC',
  'New England',
  'New York City',
  'New York RB',
  'Newcastle Jets',
  'Newcastle Jets W',
  'Newcastle United',
  'Newcastle United U19',
  "Newell's Old Boys",
  'Newport County',
  'Nice',
  'Nottingham Forest',
  'Notts County',
  'Nürnberg',
  "O'Higgins",
  'Odense BK',
  'OFI',
  'OH Leuven',
  'OH Leuven W',
  'Oldham Athletic',
  'Olympiacos F.C.',
  'Olympiacos F.C. U19',
  'Olympique Lyonnais',
  'Olympique Marseille',
  'Olympique Marseille U19',
  'Omonia Nicosia',
  'Once Caldas',
  'Ordabasy',
  'Orenburg',
  'Orlando City',
  'Orlando Pirates',
  'Osasuna',
  'Osijek',
  'Oxford United',
  'Pachuca',
  'Paços de Ferreira',
  'Paderborn',
  'Pafos FC',
  'Pafos U19',
  'Palermo',
  'Palestino',
  'Palmeiras',
  'Palmeiras W',
  'Panathinaikos',
  'PAOK',
  'PAOK U19',
  'Paris',
  'Paris Saint Germain',
  'Paris SG U19',
  'Paris SG W',
  'Parma',
  'Partick Thistle',
  'Partizan',
  'Pau',
  'Paysandu',
  'PEC Zwolle',
  'Peñarol',
  'Pendikspor',
  'Persepolis',
  'Perth Glory',
  'Perth Glory W',
  'Pescara',
  'Peterborough United',
  'Petrolul 52',
  'Philadelphia Union',
  'Piast Gliwice',
  'Pisa',
  'Platense',
  'Plymouth Argyle',
  'Pogoń Szczecin',
  'Pohang Steelers',
  'Polissya Zhytomyr',
  'Ponte Preta',
  'Port Vale',
  'Portimonense SAD',
  'Portimonense SC',
  'Portland Timbers',
  'Porto',
  'Porto U19',
  'Portsmouth',
  'Preston North End',
  'Preußen Münster',
  'PSV',
  'PSV U19',
  'PSV W',
  'Puebla',
  'Pumas UNAM',
  'Puskás',
  'Puskás Akadémia U19',
  'Pyramids FC',
  'Pyunik',
  'Qarabağ',
  'Qarabag U19',
  'Qatar SC',
  'Queens Park Rangers',
  'Querétaro',
  'Quick Boys',
  'Racing Club',
  'Racing Ferrol',
  'Racing Santander',
  'Radomiak Radom',
  'Raja Casablanca',
  'Raków Częstochowa',
  'Randers FC',
  'Rangers',
  'Rapid Bucuresti',
  'Rayo Vallecano',
  'RB Bragantino W',
  'RB Leipzig',
  'Reading',
  'Real Betis',
  'Real Betis U19',
  'Real Madrid',
  'Real Madrid U19',
  'Real Madrid W',
  'Real Oviedo',
  'Real Salt Lake',
  'Real Sociedad',
  'Real Valladolid',
  'Real Zaragoza',
  'Reggiana',
  'Reims',
  'Rennes',
  'RFC Liège',
  'Rheindorf Altach',
  'Ried',
  'Riga',
  'Riga W',
  'Rīgas FS',
  'Rijeka',
  'Rio Ave',
  'River Plate',
  'Rizespor',
  'RKC Waalwijk',
  'Rochdale',
  'Roda JC Kerkrade',
  'Roma',
  'Roma W',
  'Rosario Central',
  'Rosenborg',
  'Rosengard W',
  'Ross County',
  'Rostov',
  'Rot-Weiss Essen',
  'Rotherham United',
  'Rubin Kazan',
  'Rukh Vynnyky',
  'RWDM Brussels',
  'Saarbrücken',
  'Sabadell',
  'Sabah',
  'Sabah U19',
  'Saint-Étienne',
  'Sakaryaspor',
  'Salernitana',
  'Salford City',
  'Salzburg',
  'Salzburg U19',
  'Sampdoria',
  'Samsunspor',
  'San Diego',
  'San Lorenzo',
  'Sandefjord',
  'Sanfrecce Hiroshima',
  'Şanlıurfaspor',
  'Santa Clara',
  'Santos',
  'Santos Laguna',
  'Santos W',
  'São Bernardo',
  'São Paulo',
  'São Paulo W',
  'Sarpsborg 08',
  'Sassuolo',
  'SC Cambuur',
  'SC Freiburg',
  'SC Heerenveen',
  'Schalke 04',
  'Scotland',
  'Seattle Sounders',
  'Seoul',
  'Sepahan',
  'Servette',
  'Sevilla',
  'Shabab Al Ahli Dubai',
  'Shakhtar Donetsk',
  'Shamrock Rovers',
  'Shandong Taishan',
  'Shanghai Port',
  'Shanghai Shenhua',
  'Sheffield United',
  'Sheffield Wednesday',
  'Shelbourne',
  'Shelbourne U19',
  'Sheriff',
  'Shimizu S-Pulse',
  'Shonan Bellmare',
  'Shrewsbury Town',
  'Sigma Olomouc',
  'Silkeborg IF',
  'Sint-Truiden',
  'Sion',
  'Sirius',
  'Sivasspor',
  'SJK',
  'SK Rapid',
  'SKA Khabarovsk',
  'Slavia Prague U19',
  'Slavia Praha',
  'Slavia Praha W',
  'Slovan Bratislava',
  'Slovan Liberec',
  'Smouha',
  'Sochaux',
  'Sochi',
  'Southampton',
  'Spakenburg',
  'Sparta Praha',
  'Sparta Praha W',
  'Sparta Rotterdam',
  'Spartak Moskva',
  'Spartak Trnava',
  'Spezia',
  'Sport Recife',
  'Sport Recife W',
  'Sporting Braga',
  'Sporting Braga W',
  'Sporting Charleroi',
  'Sporting CP',
  'Sporting CP U19',
  'Sporting Cristal',
  'Sporting Gijón',
  'Sporting KC',
  'SpVgg Greuther Fürth',
  'St. Gallen',
  'St. Johnstone',
  'St. Louis City',
  'St. Mirren',
  'St. Pauli',
  'Stade Malien Bamako',
  'Stal Mielec',
  'Standard Liège',
  'Stellenbosch',
  'Stevenage',
  'Stockport County',
  'Stoke City',
  'Strasbourg',
  'Strømsgodset',
  'Sturm Graz',
  'Südtirol',
  'Sunderland',
  'SuperSport United',
  'Sutton United',
  'Suwon',
  'Swansea City',
  'Swindon Town',
  'Sydney',
  'Sydney FC W',
  'Talleres Córdoba',
  'Tampines Rovers',
  'Tenerife',
  'Teplice',
  'Ternana',
  'The New Saints',
  'The Strongest',
  'Thun',
  'Tianjin Jinmen Tiger',
  'Tigre',
  'Tigres UANL',
  'Tijuana',
  'Tirol',
  'Tokyo Verdy',
  'Toluca',
  'Tondela',
  'Torino',
  'Toronto',
  'Tottenham Hotspur',
  'Tottenham Hotspur U19',
  'Tottenham W',
  'Toulouse',
  'Trabzonspor',
  'Trabzonspor U19',
  'Tranmere Rovers',
  'Tromsø',
  'Troyes',
  'True Bangkok United',
  'TSG Hoffenheim',
  'Tunisia',
  'Tyumen',
  'UCAM Murcia',
  'UD Ibiza',
  'Udinese',
  'Ufa',
  'Ulsan HD',
  'Ümraniyespor',
  'Unión Española',
  'Union Saint-Gilloise',
  'Universidad Católica',
  'Universidad Chile',
  'Universitario',
  'Universitatea Cluj',
  'Universitatea Craiova',
  'Ural',
  'Urartu',
  'Urawa Reds',
  'UTA Arad',
  'Utrecht',
  'Uzbekistan',
  'Valencia',
  'Vålerenga',
  'Vålerenga W',
  'Valur',
  'Valur W',
  'Vancouver Whitecaps',
  'Varaždin',
  'Vasco da Gama',
  'Västerås SK',
  'Vejle Boldklub',
  'Vélez Sarsfield',
  'Venezia',
  'Veres',
  'VfB Stuttgart',
  'VfL Bochum 1848',
  'VfL Wolfsburg',
  'Viborg FF',
  'Vicenza',
  'Viking',
  'Víkingur',
  'Víkingur Reykjavík',
  'Viktoria Köln',
  'Viktoria Plzeň',
  'Villarreal',
  'Villarreal U19',
  'Vissel Kobe',
  'Vitesse',
  'Vitória',
  'Vitória Guimarães',
  'Vllaznia Shkodër',
  'Vllaznia W',
  'Volos NFC',
  'Vorskla',
  'Vorskla Poltava W',
  'VPS',
  'VVV-Venlo',
  'Wadi Degla',
  'Walsall',
  'Watford',
  'Wealdstone',
  'Wehen Wiesbaden',
  'Wellington Phoenix',
  'Wellington Phoenix W',
  'Werder Bremen',
  'West Bromwich Albion',
  'West Ham United',
  'West Ham W',
  'Westerlo',
  'Western Sydney Wanderers',
  'Western Sydney Wanderers W',
  'Western United',
  'Western United W',
  'Widzew Lodz',
  'Wigan Athletic',
  'Willem II',
  'Winterthur',
  'Woking',
  'Wolfsberger AC',
  'Wolfsburg W',
  'Wolverhampton Wanderers',
  'Wrexham',
  'WSG Tirol',
  'Wuhan Three Towns',
  'Wycombe Wanderers',
  'Wydad Casablanca',
  'Yeni Malatyaspor',
  'Yeovil Town',
  'Yokohama',
  'Yokohama F. Marinos',
  'York City',
  'Young Africans',
  'Young Boys',
  'Young Boys W',
  'Yverdon Sport',
  'Zagłębie Lubin',
  'Žalgiris',
  'Zamalek',
  'ZED FC',
  'Zeljeznicar',
  'Zenit',
  'Zhejiang',
  'Žilina',
  'Žilina U19',
  'Zimbru',
  'Zira',
  'Zlín',
  'Zob Ahan',
  'Zorya Luhansk',
  'Zrinjski',
  'Zrinjski U19',
  'Zulte-Waregem',
  'Zürich',
] as const;
