import {usePreMatchSection} from './PreMatchReportContext';
import React,{useState} from 'react';
import {Image,Pressable,StyleSheet,Text,View} from 'react-native';
import {ACCENT,LINE,MUTED,TEXT} from '@/theme';
import {type PostMatchCardData} from '@/services/matchPool';
import {MatchReportSelector} from './MatchReportPlayerAnalysis';
import ActionSpinner from './ActionSpinner';
const date=(raw:string)=>{const d=new Date(raw.replace(' ','T')+(/Z$|[+-]\d\d:\d\d$/.test(raw)?'':'Z'));return Number.isFinite(d.getTime())?d.toLocaleDateString('tr-TR',{timeZone:'Europe/Istanbul',day:'2-digit',month:'2-digit',year:'2-digit'}):'—';};
export default function PreMatchFormResults({data,tr,active}:{data:PostMatchCardData;tr:boolean;active:boolean}){
 const {result,error,loading,onRetry}=usePreMatchSection('form');
 const [teamId,setTeamId]=useState<number>();
 const teams=[...data.teams].sort((a,b)=>Number(a.location!=='home')-Number(b.location!=='home')),team=teams.find(t=>t.id===teamId)||teams[0],accent=team?.location==='away'?'#38BDF8':ACCENT;
 const usage=result?.teams.find(t=>t.team_id===team?.id),summary=usage?.summary,standing=result?.standings[String(team?.id)],results=[...(usage?.results||[])].sort((a,b)=>b.starting_at.localeCompare(a.starting_at));
 const balance=(v?:{goals_for:number;goals_against:number})=><Text style={s.value}><Text style={{color:'#22C55E'}}>{v?.goals_for??'—'}</Text> – <Text style={{color:'#EF4444'}}>{v?.goals_against??'—'}</Text></Text>;
 return <View style={{gap:15}}><View style={[s.frame,{borderColor:`${accent}70`}]}><View style={[s.rule,{backgroundColor:accent}]}/><MatchReportSelector label={tr?'Takım Seçimi':'Select Team'} value={team?.name||'—'} options={teams.map(t=>({id:t.id,name:t.name,detail:t.location==='away'?tr?'Deplasman':'Away':tr?'Ev Sahibi':'Home',color:t.location==='away'?'#38BDF8':ACCENT}))} onSelect={setTeamId} accent={accent}/></View>
 <View style={[s.frame,{borderColor:`${accent}70`}]}><View style={s.hero}>{team?.image_url&&<Image source={{uri:team.image_url}} style={s.logo} resizeMode="contain"/>}<View style={{flex:1,gap:7}}><Text style={[s.title,{color:accent}]}>{team?.name}</Text><Text style={s.caption}>{tr?'Bu sezon · Son':'This season · Last'} {usage?.sample_size??'—'} {tr?'tamamlanmış maç':'completed matches'}</Text></View></View>
 {loading?<View style={s.feedback}><ActionSpinner size={25} color={accent}/><Text style={s.caption}>{tr?'Sonuçlar yükleniyor…':'Loading results…'}</Text></View>:error?<View style={s.feedback}><Text style={s.caption}>{tr?'Sonuçlar yüklenemedi.':'Unable to load results.'}</Text><Pressable style={s.tile} onPress={onRetry}><Text style={{color:accent}}>{tr?'Tekrar Dene':'Try Again'}</Text></Pressable></View>:<>
 <Text style={s.section}>{tr?'Son Maçlar':'Recent Matches'}</Text><View style={s.row}>{[[tr?'Galibiyet':'Wins',summary?.wins,'#22C55E'],[tr?'Beraberlik':'Draws',summary?.draws,TEXT],[tr?'Mağlubiyet':'Losses',summary?.losses,'#EF4444']].map(([label,value,color])=><View key={String(label)} style={[s.tile,s.third]}><Text style={[s.value,{color:String(color)}]}>{value??'—'}</Text><Text style={s.caption}>{label}</Text></View>)}</View>
 <Text style={s.section}>{tr?'Gol Dengesi':'Goal Balance'}</Text><View style={s.row}>{[[tr?'İç Saha':'Home',summary?.home],[tr?'Deplasman':'Away',summary?.away],[tr?'Toplam':'Total',summary]] .map(([label,record])=><View key={String(label)} style={[s.tile,s.third]}><Text style={s.caption}>{String(label)}</Text>{balance(record as {goals_for:number;goals_against:number}|undefined)}</View>)}</View>
 <Text style={s.section}>{`${data.league?.name || (tr ? 'Lig' : 'League')} ${tr ? 'Sıralaması' : 'Standings'}`}</Text><View style={s.row}><View style={[s.tile,s.third]}><Text style={s.caption}>{tr?'Sıra':'Rank'}</Text><Text style={[s.value,{color:accent}]}>{standing?.position?`#${standing.position}`:'—'}</Text></View><View style={[s.tile,s.third]}><Text style={s.caption}>{tr?'Toplanan Puan':'Points Earned'}</Text><Text style={s.value}>{standing?.points??'—'}</Text></View></View>{!!standing?.table_label&&<Text style={s.caption}>{standing.table_label}</Text>}
 <Text style={s.section}>{tr?'Son Maçlar':'Recent Matches'}</Text>
 {results.map(match=>{const color=match.result==='W'?'#22C55E':match.result==='L'?'#EF4444':TEXT;const label=match.result==='W'?tr?'G':'W':match.result==='L'?tr?'M':'L':match.result==='D'?tr?'B':'D':'—';return <View key={match.fixture_id} style={s.tile}><View style={s.row}><Text style={[s.badge,{color,borderColor:`${color}70`}]}>{label}</Text>{match.opponent_image_url&&<Image source={{uri:match.opponent_image_url}} style={s.opponentLogo} resizeMode="contain"/>}<View style={{flex:1,gap:4}}><Text style={s.name}>{match.opponent_name}</Text><Text style={s.caption}>{date(match.starting_at)} · {match.location==='home'?tr?'İç Saha':'Home':tr?'Deplasman':'Away'}</Text></View><Text style={[s.score,{color}]}>{match.team_score??'—'} – {match.opponent_score??'—'}</Text></View><Text style={s.caption}>{match.league_name}</Text></View>;})}
 {!results.length&&<Text style={s.caption}>{tr?'Bu sezon için tamamlanmış maç bulunmuyor.':'No completed matches this season.'}</Text>}
 </>}
 </View>

 </View>;
}
const s=StyleSheet.create({frame:{padding:13,borderWidth:1,borderRadius:19,gap:13},rule:{height:3,borderRadius:3},hero:{flexDirection:'row',alignItems:'center',gap:13,paddingBottom:13,borderBottomWidth:1,borderBottomColor:LINE},logo:{width:53,height:60},title:{fontSize:19,fontWeight:'800',color:TEXT},caption:{fontSize:10,lineHeight:15,fontWeight:'600',color:MUTED},feedback:{paddingVertical:30,alignItems:'center',gap:15},row:{flexDirection:'row',alignItems:'center',gap:7},tile:{borderWidth:1,borderColor:LINE,borderRadius:12,padding:10,gap:7,backgroundColor:'rgba(255,255,255,.02)'},third:{flex:1,alignItems:'center',paddingHorizontal:4},value:{fontSize:21,fontWeight:'800',color:TEXT},section:{fontSize:13,fontWeight:'800',color:MUTED,marginTop:5},name:{fontSize:12,fontWeight:'700',color:TEXT},score:{fontSize:17,fontWeight:'800',color:TEXT},opponentLogo:{width:26,height:31},badge:{borderWidth:1,borderRadius:8,padding:7,fontSize:12,fontWeight:'800'}});
