import {usePreMatchSection} from './PreMatchReportContext';
import React,{useState} from 'react';
import {Image,Pressable,StyleSheet,Text,View} from 'react-native';
import {ACCENT,LINE,MUTED,TEXT} from '@/theme';
import {type PostMatchCardData} from '@/services/matchPool';
import {MatchReportSelector} from './MatchReportPlayerAnalysis';
import ActionSpinner from './ActionSpinner';
const states=[{key:'ahead',tr:'Öndeyken',en:'Ahead',color:'#22C55E'},{key:'level',tr:'Beraberlikte',en:'Level',color:'#94A3B8'},{key:'behind',tr:'Gerideyken',en:'Behind',color:'#F87171'}];
export default function PreMatchScoreFlow({data,tr,active}:{data:PostMatchCardData;tr:boolean;active:boolean}){
 const [teamId,setTeamId]=useState<number>();
 const {result,error,loading,onRetry}=usePreMatchSection('squad');
 if(error)return <View style={s.feedback}><Text style={s.caption}>{tr?'Skor akışı yüklenemedi.':'Unable to load score flow.'}</Text><Pressable style={s.tile} onPress={onRetry}><Text style={{color:ACCENT}}>{tr?'Tekrar Dene':'Try Again'}</Text></Pressable></View>;
 if(!result)return <View style={s.feedback}><ActionSpinner size={25} color={ACCENT}/><Text style={s.caption}>{tr?'Skor akışı yükleniyor…':'Loading score flow…'}</Text></View>;
 const teams=[...data.teams].sort((a,b)=>Number(a.location!=='home')-Number(b.location!=='home'));
 const selected=teams.find(t=>t.id===teamId)||teams[0];
 return <View style={{gap:16}}><View style={[s.frame,{borderColor:`${selected?.location==='away'?'#38BDF8':ACCENT}70`}]}><View style={[s.rule,{backgroundColor:selected?.location==='away'?'#38BDF8':ACCENT}]}/><MatchReportSelector label={tr?'Takım Seçimi':'Select Team'} value={selected?.name||'—'} options={teams.map(t=>({id:t.id,name:t.name,detail:t.location==='away'?tr?'Deplasman':'Away':tr?'Ev Sahibi':'Home',color:t.location==='away'?'#38BDF8':ACCENT}))} onSelect={setTeamId} accent={selected?.location==='away'?'#38BDF8':ACCENT}/></View>{teams.filter(t=>t.id===selected?.id).map(team=>{const use=result.teams.find(u=>u.team_id===team.id),accent=team.location==='away'?'#38BDF8':ACCENT;const rows=use?.score_flow?.states||[];return <View key={team.id} style={[s.frame,{borderColor:`${accent}70`}]}><View style={[s.rule,{backgroundColor:accent}]}/><View style={s.hero}>{team.image_url&&<Image source={{uri:team.image_url}} style={s.logo} resizeMode="contain"/>}<View style={{flex:1,gap:7}}><Text style={[s.title,{color:accent}]}>{team.name}</Text><Text style={s.caption}>{tr?'Bu sezon · Son':'This season · Last'} {use?.sample_size??0} {tr?'tamamlanmış maç':'completed matches'}</Text></View></View>
 {!use?.sample_size?<Text style={s.caption}>{tr?'Bu sezon tamamlanmış maç bulunmuyor.':'No completed matches this season.'}</Text>:<><View style={s.stacked}>{states.map(state=>{const share=rows.find(r=>r.key===state.key)?.share||0;return share>0?<View key={state.key} style={{flex:share,backgroundColor:state.color}}/>:null;})}</View>{states.map(state=>{const r=rows.find(r=>r.key===state.key);return <View key={state.key} style={[s.tile,{borderColor:`${state.color}60`,backgroundColor:`${state.color}09`}]}><View style={s.row}><View style={{width:8,height:8,borderRadius:4,backgroundColor:state.color}}/><Text style={[s.name,{flex:1,color:state.color}]}>{tr?state.tr:state.en}</Text><Text style={[s.percent,{color:state.color}]}>%{r?.share.toLocaleString(tr?'tr-TR':'en-US',{maximumFractionDigits:1})??'—'}</Text></View><Text style={s.minutes}>{r?.minutes.toLocaleString(tr?'tr-TR':'en-US',{maximumFractionDigits:1})??'—'} {tr?'dakika':'minutes'}</Text><View style={s.track}><View style={{height:5,borderRadius:3,backgroundColor:state.color,width:`${Math.min(100,Math.max(0,r?.share||0))}%`}}/></View></View>;})}</>}
 </View>;})}</View>;
}
const s=StyleSheet.create({frame:{borderWidth:1,borderRadius:19,padding:14,gap:14},rule:{height:3,borderRadius:3},hero:{flexDirection:'row',alignItems:'center',gap:13},logo:{width:47,height:55},title:{fontSize:20,fontWeight:'800',color:TEXT},caption:{color:MUTED,fontSize:11,lineHeight:17},feedback:{paddingVertical:45,alignItems:'center',gap:15},tile:{borderWidth:1,borderColor:LINE,borderRadius:13,padding:12,gap:9},stacked:{flexDirection:'row',height:18,borderRadius:9,overflow:'hidden',gap:2,marginVertical:4},row:{flexDirection:'row',alignItems:'center',gap:8},name:{fontSize:14,fontWeight:'700'},percent:{fontSize:22,fontWeight:'800'},minutes:{color:TEXT,fontSize:13,fontWeight:'600'},track:{height:5,borderRadius:3,overflow:'hidden',backgroundColor:'rgba(255,255,255,.07)'}});
