import {usePreMatchSection} from './PreMatchReportContext';
import React,{useState} from 'react';
import {Image,Pressable,StyleSheet,Text,View} from 'react-native';
import {ACCENT,LINE,MUTED,TEXT} from '@/theme';
import {type PreMatchMomentumRow,type PostMatchCardData} from '@/services/matchPool';
import ActionSpinner from './ActionSpinner';
import TeamReportLockedDetail from './TeamReportLockedDetail';
function trend(value:number,rows:PreMatchMomentumRow[],tr:boolean){const values=rows.map(r=>Math.abs(r.average_net_pressure)).filter(v=>v>Number.EPSILON).sort((a,b)=>a-b);if(!values.length)return {label:'—',color:MUTED};const balanced=values[Math.floor((values.length-1)*.25)]||Number.EPSILON,strong=values[Math.floor((values.length-1)*.75)]||balanced;return Math.abs(value)<balanced?{label:tr?'Dengeli':'Balanced',color:MUTED}:value>=strong?{label:tr?'Belirgin üstünlük':'Clear dominance',color:'#22C55E'}:value>0?{label:tr?'Hafif üstünlük':'Slight dominance',color:'#86EFAC'}:Math.abs(value)>=strong?{label:tr?'Baskı kaybı':'Pressure lost',color:'#EF4444'}:{label:tr?'Hafif gerileme':'Slight decline',color:'#FCA5A5'};}
export default function PreMatchMomentum({data,tr,active,free,onOpenPlans}:{data:PostMatchCardData;tr:boolean;active:boolean;free:boolean;onOpenPlans:()=>void}){
 const {result,error,loading,onRetry}=usePreMatchSection('momentum');
 const teams=[...data.teams].sort((a,b)=>Number(a.location!=='home')-Number(b.location!=='home')).slice(0,2);
 const periods=Array.from({length:10},(_,i)=>i===9?'90+':`${i===0?0:i*10+1}-${(i+1)*10}`);
 if(loading||!result&&!error)return <View style={s.feedback}><ActionSpinner size={25} color={ACCENT}/><Text style={s.caption}>{tr?'Momentum hazırlanıyor…':'Preparing momentum…'}</Text></View>;
 if(error)return <View style={s.feedback}><Text style={s.caption}>{tr?'Momentum yüklenemedi.':'Unable to load momentum.'}</Text><Pressable style={s.frame} onPress={onRetry}><Text style={{color:ACCENT}}>{tr?'Tekrar Dene':'Try Again'}</Text></Pressable></View>;
 return <View style={{gap:15}}>
 {!free&&<View style={[s.frame,{borderColor:'#FCD34D66',backgroundColor:'#FCD34D08'}]}><View style={[s.rule,{backgroundColor:'#FCD34D'}]}/><Text style={[s.title,{color:'#FCD34D'}]}>{tr?'ScoutWise Perspektifi':'ScoutWise Perspective'}</Text><Text style={{color:TEXT,fontSize:13,fontWeight:'700'}}>{tr?'Maç Okuması':'Match Outlook'}</Text><Text style={s.body}>{result?.perspective?.match_outlook||(tr?'Bu maç için baskı değerlendirmesi oluşturacak yeterli veri bulunmuyor.':'Insufficient pressure data for a match outlook.')}</Text></View>}
 <View style={s.frame}><View style={s.rule}/><Text style={s.title}>{tr?'10 Dakikalık Baskı Özeti':'10-minute Pressure Summary'}</Text><View style={s.legend}><Text style={[s.goal,{borderColor:'#4ADE80'}]}>⚽ <Text style={{color:'#4ADE80'}}>{tr?'Atılan':'Scored'}</Text></Text><Text style={[s.goal,{borderColor:'#FB7185'}]}>⚽ <Text style={{color:'#FB7185'}}>{tr?'Yenilen':'Conceded'}</Text></Text></View>
 <View style={s.table}><View style={s.row}><Text style={[s.minute,s.caption]}>{tr?'Dakika':'Minutes'}</Text>{teams.map(t=><View key={t.id} style={s.team}>{t.image_url&&<Image source={{uri:t.image_url}} style={s.logo} resizeMode="contain"/>}<Text style={[s.teamName,{color:t.location==='away'?'#38BDF8':ACCENT}]}>{t.name}</Text><Text style={s.caption}>{tr?'Baskı Eğilimi':'Pressure Trend'}</Text></View>)}</View>
 {periods.map((period,i)=><View key={period} style={[s.row,i%2===1&&{backgroundColor:'rgba(255,255,255,.025)'}]}><Text style={[s.minute,s.period]}>{period}′</Text>{teams.map(t=>{const rows=result?.teams.find(u=>u.team_id===t.id)?.momentum||[],row=rows.find(r=>r.period===period);const info=trend(row?.average_net_pressure||0,rows,tr);return <View key={t.id} style={s.cell}><View style={s.inline}>{!row?.goals_for && !row?.goals_against && <Text style={s.caption}>—</Text>}{!!row?.goals_for&&<Text accessibilityLabel={`${row.goals_for} ${tr?'atılan gol':'goals scored'}`} style={[s.goal,{borderColor:'#4ADE80'}]}>⚽<Text style={{color:'#4ADE80'}}> ×{row.goals_for}</Text></Text>}{!!row?.goals_against&&<Text accessibilityLabel={`${row.goals_against} ${tr?'yenilen gol':'goals conceded'}`} style={[s.goal,{borderColor:'#FB7185'}]}>⚽<Text style={{color:'#FB7185'}}> ×{row.goals_against}</Text></Text>}</View><Text style={[s.trend,{color:info.color}]}>{info.label}</Text></View>;})}</View>)}
 </View></View>{free&&<TeamReportLockedDetail tr={tr} accent="#FCD34D" kind="momentum" onOpenPlans={onOpenPlans}/>}</View>;
}
const s=StyleSheet.create({frame:{padding:12,borderWidth:1,borderColor:`${ACCENT}70`,borderRadius:18,gap:13},rule:{height:3,backgroundColor:ACCENT,borderRadius:3},title:{color:ACCENT,fontSize:18,fontWeight:'800'},body:{color:TEXT,fontSize:13,lineHeight:22},caption:{color:MUTED,fontSize:10,textAlign:'center',lineHeight:15},feedback:{paddingVertical:45,alignItems:'center',gap:15},table:{borderWidth:1,borderColor:LINE,borderRadius:13,overflow:'hidden'},row:{flexDirection:'row',borderBottomWidth:1,borderBottomColor:LINE},minute:{width:48,textAlign:'center',alignSelf:'center',paddingHorizontal:2},period:{color:TEXT,fontSize:10,fontWeight:'800'},team:{flex:1,alignItems:'center',padding:9,gap:7},logo:{width:30,height:36},teamName:{fontSize:11,fontWeight:'800',textAlign:'center'},cell:{flex:1,borderLeftWidth:1,borderLeftColor:LINE,paddingHorizontal:4,paddingVertical:12,gap:8,justifyContent:'flex-start'},inline:{minHeight:28,flexDirection:'row',flexWrap:'nowrap',justifyContent:'center',alignItems:'center',gap:5},value:{fontSize:13,fontWeight:'800'},trend:{minHeight:54,fontSize:12,lineHeight:18,textAlign:'center',fontWeight:'800',borderWidth:1,borderColor:LINE,borderRadius:9,paddingVertical:8,paddingHorizontal:3,backgroundColor:'rgba(255,255,255,.04)'},goal:{borderWidth:1,borderRadius:8,padding:4,fontSize:10,color:TEXT,backgroundColor:'rgba(0,0,0,.2)'},legend:{flexDirection:'row',gap:10,justifyContent:'center'}});
