import React from 'react';
import {Modal,Pressable,StyleSheet,Text,View,ScrollView} from 'react-native';
import {BadgeCheck} from 'lucide-react-native';
import {useNavigation} from '@react-navigation/native';
import PlanManagementButton from './PlanManagementButton';
import {ACCENT,CARD,LINE,MUTED,PANEL,TEXT} from '@/theme';
export default function SimilarPlayersUpgradeModal({required,tr,onClose}:{required:'plus'|'pro'|'done';tr:boolean;onClose:()=>void}){
  const nav=useNavigation<any>();
  return <Modal visible transparent animationType="fade" onRequestClose={onClose}><View style={s.backdrop}><View style={s.panel} accessibilityViewIsModal><ScrollView contentContainerStyle={{gap:16}}><View style={s.header}><BadgeCheck size={24} color={ACCENT}/><Text style={s.title}>{required==='done'?(tr?'Tüm Profiller Gösterildi':'All Profiles Shown'):required==='pro'?<>{tr?'':'More Similar Players with '}<Text style={s.pro}>PRO</Text>{tr?' ile Daha Fazla Benzer Oyuncu':''}</>:(tr?'Daha Fazla Benzer Oyuncu':'More Similar Players')}</Text></View><Text style={s.body}>{required==='done'?(tr?'Bu aramada gösterilebilecek profilleri gördün. Daha fazla sonuç için kriterlerini genişletebilirsin.':'You have seen all available profiles for this search. Broaden your criteria to find more results.'):required==='pro'?<>{tr?'':'You have reached the '}<Text style={s.plus}>PLUS</Text>{tr?' planındaki 6 oyuncu sınırına ulaştın.':' limit of 6 players.'}</>:<>{tr?'':'Upgrade to '}<Text style={s.plus}>PLUS</Text>{tr?' veya ':' or '}<Text style={s.pro}>Pro</Text>{tr?'’ya yükselterek daha fazla benzer oyuncuyu inceleyebilirsin.':' to explore more similar players.'}</>}</Text>{required!=='done'&&<View style={{gap:8}}>{required==='plus'&&<View style={s.planRow}><Text style={s.plus}>PLUS</Text><Text style={s.body}>{tr?'En fazla 6 oyuncu':'Up to 6 players'}</Text></View>}<View style={s.planRow}><Text style={s.pro}>PRO</Text><Text style={s.body}>{tr?'En fazla 15 oyuncu':'Up to 15 players'}</Text></View></View>}<View style={s.actions}>{required==='done'?<PlanManagementButton label={tr?'Tamam':'OK'} onPress={onClose}/>:<Pressable accessibilityRole="button" onPress={onClose} style={s.later}><Text style={s.body}>{tr?'Şimdi Değil':'Not Now'}</Text></Pressable>}{required!=='done'&&<PlanManagementButton onPress={()=>{onClose();setTimeout(()=>nav.navigate('Profile',{screen:'ManagePlan'}),350);}}/>}</View></ScrollView></View></View></Modal>;
}
const s=StyleSheet.create({backdrop:{flex:1,justifyContent:'center',padding:24,backgroundColor:'rgba(0,0,0,.72)'},panel:{width:'100%',maxWidth:560,maxHeight:'90%',alignSelf:'center',backgroundColor:PANEL,borderRadius:22,borderWidth:1,borderColor:ACCENT,padding:22,gap:16},header:{flexDirection:'row',alignItems:'center',gap:12},title:{flex:1,color:TEXT,fontSize:19,lineHeight:25,fontWeight:'800'},body:{color:MUTED,fontSize:14,lineHeight:21},planRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,borderWidth:1,borderColor:LINE,borderRadius:12,padding:12},plus:{color:'#38BDF8',fontWeight:'900'},pro:{color:ACCENT,fontWeight:'900'},actions:{flexDirection:'row',flexWrap:'wrap',gap:10},later:{flex:1,minHeight:44,borderWidth:1,borderColor:LINE,borderRadius:12,padding:10,alignItems:'center',justifyContent:'center',backgroundColor:CARD}});
