// Same tactical labels as ScoutWise enterprise.
export const reportPhaseLabels: Record<string, string> = {
  "Safe-Passing Goalkeeper": "Güvenli Pas Kalecisi",
  "Long-Distribution Goalkeeper": "Uzun Oyun Başlatan Kaleci",
  "Playmaking Goalkeeper": "Oyun Kurucu Kaleci",
  "Line Goalkeeper": "Çizgi Kalecisi",
  "Box-Commanding Goalkeeper": "Ceza Sahası Hakimi",
  "Last-Action Goalkeeper": "Son Müdahale Kalecisi",
  "Defense-Pinning Forward": "Savunmayı Geride Tutan Forvet",
  "Long-Ball Target": "Uzun Top Hedefi",
  "Depth-Running Forward": "Derin Koşu Forveti",
  "Ball-Securing Forward": "Top Koruyan Forvet",
  "Link Forward": "Bağlantı Forveti",
  "Finishing Forward": "Bitirici Forvet",
  "Service Forward": "Servis Yapan Forvet",
  "Front-Line Presser": "Ön Alan Presçisi",
  "Passing-Lane Blocker": "Pas Kanalı Kapatıcısı",
  "Holding-Midfield Blocker": "Ön Libero Kapatıcısı",
  "Transition Threat": "Geçiş Tehdidi",
  "Physical Front-Line Defender": "Fiziksel Ön Hat Savunucusu",
  "Counter-Outlet Forward": "Kontra Çıkış Forveti",
  "Set-Piece Defender": "Duran Top Savunucusu",
  "Hold-Up Outlet Forward": "Top Tutup Takımı Çıkaran Forvet",
  "Width-Holding Winger": "Genişlik Sağlayan Kanat",
  "Link-Up Winger": "Pas Bağlantısı Kuran Kanat",
  "One-v-One Winger": "Bire Bir Kanadı",
  "Progressive Winger": "İlerletici Kanat",
  "Combination Winger": "Kombinasyon Kanadı",
  "Touchline Creator": "Çizgi Üreticisi",
  "Inside Forward": "İç Forvet",
  "Creative Winger": "Yaratıcı Kanat",
  "Full-Back Presser": "Bek Presçisi",
  "Wide Passing-Lane Blocker": "Kanat Pas Kanalı Kapatıcısı",
  "High Ball-Winning Winger": "Önde Top Kazanan Kanat",
  "Tracking Winger": "Geri Dönen Kanat",
  "Channel Defender": "Koridor Savunucusu",
  "Transition Winger": "Geçiş Kanadı",
  "Full-Back Supporter": "Bek Destekçisi",
  "Back-Post Defender": "Arka Direk Savunucusu",
  "Counter Carrier": "Kontra Taşıyıcısı",
  "Between-Lines Connector": "Hatlar Arası Bağlantı Oyuncusu",
  "Drifting Playmaker": "Genişleyen Oyun Kurucu",
  "Between-Lines Playmaker": "Çizgiler Arası Oyun Kurucu",
  "Through-Ball Specialist": "Ara Pas Uzmanı",
  "Central Dribbler": "Merkez Driplingcisi",
  "Final-Pass Creator": "Son Pas Oyuncusu",
  "Second Forward": "İkinci Forvet",
  "Shooting Threat": "Şut Tehdidi",
  "Pivot-and-Center-Back Presser": "Ön Libero ve Stoper Presçisi",
  "Second-Ball Collector": "İkinci Top Toplayıcısı",
  "Ball-Winning Creator": "Top Kazanıp Yaratıcılık Üreten Oyuncu",
  "Central Passing-Lane Blocker": "Merkez Pas Kanalı Kapatıcısı",
  "Press Trigger": "Pres Tetikleyicisi",
  "Transition Playmaker": "Geçiş Oyun Kurucusu",
  "Box-Edge Defender": "Ceza Sahası Önü Savunucusu",
  "Second-Ball Playmaker": "İkinci Top Oyun Kurucusu",
  "Counter Initiator": "Kontra Başlatıcısı",
  "First-Pass Player": "İlk Pas Oyuncusu",
  "Press-Breaking Passer": "Pres Kıran Pasör",
  "Central Ball Carrier": "Top Taşıyan Merkez",
  "Vertical Passer": "Dikey Pasör",
  "Play Director": "Oyun Yönlendirici",
  "Front-Line Connector": "Ön Hat Bağlantı Oyuncusu",
  "Box-Arriving Midfielder": "Ceza Sahasına Koşu Yapan Orta Saha",
  "Attack-Sustaining Player": "Hücum Sürekliliği Oyuncusu",
  "Second-Ball Winner": "İkinci Top Kazanan",
  "Counter-Presser": "Karşı Pres Oyuncusu",
  "Space Protector": "Alan Koruyucusu",
  "Duel Specialist": "İkili Mücadele Uzmanı",
  "Box-Edge Protector": "Ceza Sahası Önü Koruyucusu",
  "Transition Stopper": "Geçiş Durdurucusu",
  "Defensive Link Player": "Savunma Bağlantı Oyuncusu",
  "First-Pass Specialist": "İlk Pas Uzmanı",
  "Switch-of-Play Player": "Oyun Yönü Değiştirici",
  "Vertical Playmaker": "Dikey Oyun Kurucu",
  "Tempo Controller": "Tempo Kontrolcüsü",
  "Balance Player": "Denge Oyuncusu",
  "Rest-Defense Player": "Geri Güvenlik Oyuncusu",
  "Scoring Final-Third Contributor": "Skorer Ön Alan Katılımcısı",
  "Attack Redirector": "Hücumu Yeniden Yönlendiren Oyuncu",
  "Press-Cover Player": "Pres Arkası Güvenlik Oyuncusu",
  "Central Presser": "Merkez Presçisi",
  "Counter Breaker": "Kontra Kesici",
  "Box-Edge Sweeper": "Ceza Sahası Önü Süpürücüsü",
  "Box Second-Ball Controller": "İkinci Top Kontrolcüsü",
  "Wide Outlet Full-Back": "Geniş Çıkış Beki",
  "Safe-Passing Full-Back": "Güvenli Pas Beki",
  "Ball-Carrying Full-Back": "Top Taşıyan Bek",
  "Overlapping Full-Back": "Bindirme Beki",
  "Combination Full-Back": "Kombinasyon Beki",
  "Progressive Full-Back": "İlerletici Bek",
  "Crossing Full-Back": "Orta Yapan Bek",
  "Back-Pass Outlet": "Geri Pas Üreticisi",
  "Inverted-Channel Full-Back": "İç Koridoru Kullanan Bek",
  "High-Pressing Full-Back": "Önde Basan Bek",
  "Wide Ball-Winning Full-Back": "Kanatta Top Kazanan Bek",
  "High-Line Defender": "Yüksek Hat Savunucusu",
  "Run Tracker": "Koşu Takipçisi",
  "Box One-v-One Defender": "Ceza Sahası Bire Bir Savunucusu",
  "Danger Clearer": "Tehlike Uzaklaştırıcı",
  "Safe Playmaking Center-Back": "Güvenli Oyun Kurucu Stoper",
  "Line-Breaking Center-Back": "Hat Kıran Stoper",
  "Ball-Carrying Center-Back": "Top Taşıyan Stoper",
  "Vertical-Passing Center-Back": "Dikey Pasör Stoper",
  "Switching Center-Back": "Oyun Yönü Değiştiren Stoper",
  "Defensive-Balance Center-Back": "Savunma Dengesi Stoperi",
  "Set-Piece Threat": "Duran Top Tehdidi",
  "Rest-Attack Collector": "Hücum Arkası Toplayıcı",
  "Counter Stopper": "Kontra Durdurucu",
  "High-Line Center-Back": "Yüksek Hat Stoperi",
  "Long-Ball Defender": "Uzun Top Savunucusu",
  "Depth Defender": "Derinlik Savunucusu",
  "Forward Marker": "Forvet Markajcısı",
  "Through-Ball Defender": "Ara Pas Savunucusu",
  "Defensive Organizer": "Savunma Organizatörü",
  "Box Defender": "Ceza Sahası Savunucusu",
  "Aerial Dominator": "Hava Hakimi",
  "Last-Action Center-Back": "Son Müdahale Stoperi"
};
